services:
  - type: web
    name: ats-web
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn ats_project.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: DJANGO_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: ats_postgres
          property: connectionString
    plan: free
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /health/
