databases:
  - name: ats_postgres
    databaseName: ats_database
    user: ats_user
    plan: free

services:
  - type: web
    name: ats-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: ats_postgres
          property: connectionString
    numInstances: 1
    healthCheckPath: /health/
