services:
  - type: web
    name: ats-web
    env: docker
    dockerCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      gunicorn ats_project.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: ats_postgres
          property: connectionString
    plan: free
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /health/
